# https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRewrite
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-prod
  namespace: myistio
spec:
  gateways:
    - istio-tangx-in
  hosts:
    - svc-prod
    - istio.tangx.in
  http:
  - name: "v1-subset"
    route:                  # 同一个 route 下面的两个 destination
    - destination:
        host: svc-prod
        subset: subset-groupv1
      weight: 25
    - destination:
        host: svc-prod
        subset: subset-groupv2
      weight: 75

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dr-prod
spec:
  host: svc-prod
  subsets:
  - name: subset-groupv1
    labels:
      version: v1
  - name: subset-groupv2
    labels:
      version: v2