# 12. header 操作

### default request without header
GET http://istio.tangx.in/review/header

### default request
GET http://istio.tangx.in/review/header
header-injection: anything


###  header operation
GET http://istio.tangx.in/header/review/header
# anything, 被 envoy 覆盖
header-injection: user-request
# header-exist if-overwrite, 被 envoy 追加
header-add-exist: header-exist
# 不存在， 被 envoy 删除
header-should-remove: anything 