# version=v1.0.0 version_major=v1  envsubst < scripts/deployment/prod.yml.tmpl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prod 
    version: v1
  name: prod-v1
  namespace: myistio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod
      version: v1
  template:
    metadata:
      labels:
        app: prod
        version: v1
    spec:
      containers:
      - image: uyinn28/istio-in-action-prod:v1.0.0
        name: prod
        resources: {}

