# version=v2.0.0 version_major=v2  envsubst < scripts/deployment/prod.yml.tmpl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prod 
    version: v2
  name: prod-v2
  namespace: myistio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod
      version: v2
  template:
    metadata:
      labels:
        app: prod
        version: v2
    spec:
      containers:
      - image: uyinn28/istio-in-action-prod:v2.0.0
        name: prod
        resources: {}

