---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prod 
    version: ${version_major}
  name: prod-${version_major}
  namespace: myistio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod
      version: ${version_major}
  template:
    metadata:
      labels:
        app: prod
        version: ${version_major}
    spec:
      containers:
      - image: uyinn28/istio-in-action-prod:${version}
        name: prod
        resources: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: prod
    version: ${version_major}
  name: svc-prod
  namespace: myistio
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: prod
  type: ClusterIP

